# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

# Sự kiện nào xảy ra thì sẽ chạy workflows này
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Định nghĩa các công việc muốn workflows tự động chạy
jobs:
  build:

    #Setup OS cho server để deploy
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    #Các bước của actions
    steps:
    - uses: actions/checkout@v4 #github action toolkit
    - name: Use Node.js ${{ matrix.node-version }} #Tên của step
      uses: actions/setup-node@v4 #github action toolkit
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci #npm clean install --> Không làm thay đổi file package.lock, giữ cho app chạy ổn định
    - run: npm run build --if-present
    - run: npm test
